# Site settings
title: Purnanand Elango
description: Ph.D. Student at University of Washington

# Build settings
theme: minima

nav:
  - title: Home
    url: /
  - title: Tools
    url: /tools/
  - title: Research
    url: /research/

footer_content: "Copyright &copy; Purnanand Elango"