# Site settings
title: Purnanand Elango
description: Ph.D. Student at University of Washington

# Build settings
theme: minima

nav:
  - title: Home
    url: /
  - title: Tools
    url: /tools/
  - title: Research
    url: /research/

footer:
  - text: Copyright © 2023 Purnanand Elango
  - text: Powered by Jekyll and GitHub Pages